# tickers: [ES, BTC-USD, ETH-USD]
# tickers: [CVX, XOM, RDS-A, RDS-B, TOT, BP, BTC-USD, ETH-USD]
tickers: [CL=F, EURUSD=X, BTC-USD, GC=F, TSLA]
tickers_desc:
  - CL=F: 'Цена за баррель сырой нефти в долларах'
  - EURUSD=X: 'Цена евро к доллару'
  - BTC-USD: 'Цена биткоина в долларах'
  - GC=F: 'Цена золота в долларах'
  - TSLA: 'Цена акции компании Tesla в долларах'

#models: [test, fourier, wavelet, baseline, arima, var]
models: [test, wavelet, baseline, arima, var]
n_pred: 10
n_trade: 3
models_trade: [logistic, ridge, dummy]
trade_budget: 15000
thresh_trade_hist: 5
trade_instrument_hist: BTC-USD
trade_imbalance_freq: 500
date_start: '2020-01-01'
date_end: '2020-12-30'
metrics: [MAE, MAPE]
