#tickers: [ES, BTC-USD, ETH-USD]
tickers: [CVX, XOM, RDS-A, RDS-B, TOT, BP, BTC-USD, ETH-USD]
models: [test, fourier, wavelet, baseline, arima, var]
n_pred: '10'
date_start: '2020-06-01'
date_end: '2020-10-05'
metrics: [MAE, MAPE]