configfile: 'workflow/config.yaml' # noqa

include: 'rules/download_data.smk'
include: 'rules/forecast.smk'
include: 'rules/reports.smk'
include: 'rules/process_data.smk'

rule all:
    input:
        'dag.svg',
        expand('reports\\figures_raw\\{ticker}.png', ticker=config['tickers']),
        expand('reports\\forecast_{model}\\{ticker}.csv', ticker=config['tickers'], model=config['models']),
        expand('reports\\meta_forecast_stacking\\{ticker}.csv', ticker=config['tickers']),
        expand('reports\\forecast\\{ticker}.csv', ticker=config['tickers']),
        expand('reports\\figures_pred\\{ticker}.png', ticker=config['tickers']),
        expand('data\\processed\\trade\\{ticker}.csv', ticker=config['tickers']),
        expand('reports\\trade\\window_sizes\\{ticker}.json', ticker=config['tickers']),
        expand('reports\\trade\\forecast\\{ticker}.json', ticker=config['tickers']),
        expand('reports\\trade\\figures_accuracy\\{ticker}.png', ticker=config['tickers']),
        # expand('reports\\simulation\\logs\\{ticker}_{model_type}.csv', ticker=config['tickers'], model_type=config['models_trade']),
        # expand('reports\\metrics\\metrics_{ticker}.csv', ticker=config['tickers']),
        'reports\\trade\\simulation\\result.csv',
        'data\\processed\\all.csv',
        'reports\\diploma.tex',
        'spbu_diploma\\main_example.pdf',
        'reports\\metrics\\best_metrics.csv',
    shell:
         'echo Ready && telegram-send Готово!'

rule generate_dag:
    output: 'dag.svg'
    shell: 'snakemake --dag spbu_diploma/main_example.pdf | dot -Tsvg > dag.svg'