configfile: 'workflow/config.yaml' # noqa

include: 'rules/download_data.smk'
include: 'rules/forecast.smk'
include: 'rules/reports.smk'

rule all:
    input:
        expand('reports/figures_raw/{ticker}.png', ticker=config['tickers']),
        expand('reports/forecast_fourier/{ticker}.csv', ticker=config['tickers']),
        expand('reports/forecast_wavelet/{ticker}.csv', ticker=config['tickers'])
    shell:
         'echo Ready'