version: "3.8"
services:
  data_loader:
    build: data_loader
    ports:
      - "5001:5000"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db
    restart: always
    networks:
      - local
  forecaster:
    build: forecaster
    ports:
      - "5000:5000"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: forecaster_db
      POSTGRES_PORT: 5433
      DATA_LOADER_HOST: data_loader
      DATA_LOADER_PORT: 5000
    depends_on:
      - forecaster_db
    restart: always
    networks:
      - local
  redis:
    image: "redis:alpine"
    networks:
      - local
  db:
    image: postgres
    restart: always
    ports:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: data_loader
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - local
  forecaster_db:
    image: postgres
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: forecaster
      PGPORT: 5433
    volumes:
      - forecaster_db_data:/var/lib/postgresql/forecaster_data
    networks:
      - local
volumes:
  database_data:
    driver: local
  forecaster_db_data:
    driver: local
networks:
  local:
    driver: bridge