name: time-series-forecasting
channels:
- defaults
- plotly
dependencies:
- python=3.8
- pandas
- numpy
- scipy
- click
- scikit-learn
- matplotlib
- seaborn
- plotly
- plotly-orca
- pip
- pip:
    - yfinance
    - snakemake
    - pdflatex
    - telegram-send
    - pmdarima
    - pywavelets