name: data_loader
channels:
- defaults
dependencies:
- python=3.8
- flask
- gunicorn
- redis
- redis-py
- pip
- pip:
    - flask-restful
    - yfinance
    - psycopg2-binary
    - Flask-SQLAlchemy
    - --extra-index-url https://test.pypi.org/simple/
    - simple-ts-forecast
    - flask-cors