version: "3.8"
services:
  data_loader:
    build: .
    ports:
      - "5000:5000"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
  redis:
    image: "redis:alpine"
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local