name: data_loader
channels:
- defaults
dependencies:
- python=3.8
- flask
- gunicorn
- redis
- redis-py
- pandas
- pip
- pip:
    - flask-restful
    - yfinance
    - psycopg2-binary
    - Flask-SQLAlchemy